title: Researcher
url: "https://ligangudel.github.io"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

# footer: yes
# footer_url: "https://ligangudel.github.io"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
