title: Gang Li
url: "https://ligangudel.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
# footer_url: "https://ligangudel.github.io"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "LinkedIn"
   link: "https://linkedin.com/in/ligangudel"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=gmBt9v8AAAAJ&hl=en"
